# frozen_string_literal: true

class Settings
  EXAMPLE_HOST = ENV['EXAMPLE_HOST'] || '192.168.3.195'
  EXAMPLE_PORT = ENV['EXAMPLE_PORT'] || 9292
  EXAMPLE_URL = "http://#{EXAMPLE_HOST}:#{EXAMPLE_PORT}"

  DOCUMENTSERVER_HOST = ENV['DOCUMENTSERVER_HOST'] || EXAMPLE_HOST
  DOCUMENTSERVER_PORT = ENV['DOCUMENTSERVER_PORT'] || 8000
  DOCUMENTSERVER_UPL = "http://#{DOCUMENTSERVER_HOST}:#{DOCUMENTSERVER_PORT}"
end
